version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "09:30"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"