name: Build Frontend

on:
  push:
    branches: master
  pull_request: 
    types: [opened, synchronise, reopened, ready_for_review]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Use Pnpm as package manager
        uses: pnpm/action-setup@v4.0.0
        with:
          version: '9.x'
      - name: Use Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "22.11.x"
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies and build
        run: pnpm install && pnpm build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload node_modules and dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dependencies-and-build
          path: dist/
          retention-days: 3